### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by U-ki-M** [U-ki-M/furima-36120#9]
## URL
https://furima-36120.herokuapp.com/

## Basic認証のIDとパスワード
ID: yuki　パスワード: 1985

## ユーザー1 emalとパスワード
murayama@gmail.com  /  mura12

## ユーザー2 emalとパスワード
yuki@gmail.com  /  yuki12

**Comment by takumi0530** [comment]
@U-ki-M さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **商品購入ページでは、一覧や詳細ページで選択した商品の情報（商品名・商品画像・販売金額・配送料負担）が、見本アプリと同様の形で出力されること**
商品名が表示されていません。
<img width="557" alt="スクリーンショット 2021-07-26 10 53 31" src="https://user-images.githubusercontent.com/76197191/126922833-f39447cd-8f4a-4be3-8695-03257196f172.png">

- [x] **ログイン状態の出品者のみ、出品した商品情報を削除できること**
削除ボタンを押すと、エラーページに遷移してしまい、削除できませんでした。
<img width="561" alt="スクリーンショット 2021-07-26 10 55 34" src="https://user-images.githubusercontent.com/76197191/126922906-9f1f7a87-0779-4582-a0b5-303876b87f4f.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by U-ki-M** [comment]
上記二点修正致しました完了報告フォームを再提出いたします。

**Comment by takumi0530** [comment]
@U-ki-M さん、お待たせいたしました。再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/126930552-4b14b305-8e18-4309-aaec-61d9eec6ed0f.png)
